### ISSUE TITLE
Issue with ModifyRegularOrder or CancelRegularOrder

### ISSUE THREAD

**Issue by crakhi** [howutrade/kotak-trader#1]
When I am trying to modify an existing LIMIT order to SL-M or SL order using the OrderId. I am getting the below error
Same error while cancelling the order also.

`System.NullReferenceException: 'Object reference not set to an instance of an object.'`

Eg:
`               Kotak.ModifyRegularOrder("1220215032201", "SL-M", 1, 0, e.LTP - 50);`

When I get this error, If I go to KOTAK website and check the pending orders, I can still see my LIMIT order with same orderID is in pending status.

Can someone pls help

![image](https://user-images.githubusercontent.com/12002009/153998611-e0f4701e-be2b-4a74-ba53-90795489940d.png)

**Comment by botany02** [comment]
@crakhi 
Make sure the Kotak class is declared with global scope and instantiated. Also note you can not convert a LIMIT order to SL/SL-M order, it's not allowed by Oms/Exchange.

**Comment by crakhi** [comment]
> @crakhi Make sure the Kotak class is declared with global scope and instantiated. Also note you can not convert a LIMIT order to SL/SL-M order, it's not allowed by Oms/Exchange.

@botany02 
Point Noted: Conversion of LIMIT to SL/SL-M is not allowed

But Order cancellation is also failing as shown in the screenshot, Kotak class is declared globally already and its been used in many places!

**Comment by botany02** [comment]
Then it may be the **transaction.SellId is null.** Could you post the complete stack trace here? also if possible attach your project files.
