### ISSUE TITLE
Please help with excel plugin

### ISSUE THREAD

**Issue by gmarwaha77** [howutrade/kotak-trader#2]
I have registered for API access with Kotak on the portal https://tradeapi.kotaksecurities.com/. I watched the videos on your channel but am facing issues:

1) In excel, where do I set the user ID and token information? Are there global settings or a menu as I cannot see any menu?
2) By default none of the downloaded samples are running as shown in video I feel probably because of the user ID and password?
3) When I open the application "Kotak Trader v1.0" nd enter the login details there I get an error "04:46:02.882 RITU_RITU ONETIMETOKEN The remote server returned an error: (500) Internal Server Error."

Please help as I cannot find anything in the online documents uploaded to Github.

If you may please share a document which can answer the following in steps:

1. After setup of Kotak trader what is to be done?
2. When I open the sample excel files where do we setup credentials?
3. If I need to call the order API from my excel file where can I get the sample?
4. Will I need to add dependency to my excel file for the DLL installed?
5. Do I need refresh token for API access or is it managed internally?

**Comment by botany02** [comment]
Hi Gaurav,

If you want to use just bridge i.e. (place orders from Excel or Amibroker)
1. Download and install the Bridge Setup from https://howutrade.in/downloads/#kotaknet (An shortcut will be created in Desktop for KotakTrader.exe)
2. Run KotakTrader.exe as Admin, enter your API credentials in Settings (one time), do login in KotakTrader (for login issue contact Kotak API team)
3. You can get started with our Bridge Samples which can be found at "C:\Program Files\KotakTrader\Examples" after installation.

You do not need to enter your user id or credentials in Excel, it needs to be entered in KotakTrader only.
KotakTrader will act as a frontend to login and receive signals from Excel/Amibroker through Bridge.

Check this short video https://twitter.com/howutrade/status/1537706338171731968

List of functions supported by Bridge
https://howutrade.github.io/kotaknet-doc/html/Methods_T_KotakNet_Bridge_Bridge.htm

For API subscription and issues, contact Kotak team at [ks.apihelp@kotak.com](mailto:ks.apihelp@kotak.com) and for trading system development in Excel, you can hire a developer or contact us for a quote.

**Comment by gmarwaha77** [comment]
Sir thanks for responding so what you imply is if Kotak trader (which I have downloaded) works that is I am able to login with OAUTH credentials then excel will also work automatically? Right now I entered the credentials and from API portal of Kotak I am able to hit their API but from the Kotak trader.exe file I am not the credentials are same and token is valid.

Do I always have to use your excel or can I include your classes to my excel as I already have the model/ signals in my excel?

I am getting ONE_TIME_TOKEN failed error

Sir is this released for Kotak customers or this is a teaser to hire developers from your company with incomplete code? Please confirm as this is not usable/ working.

**Comment by botany02** [comment]
For login issue (i.e. ONE_TIME_TOKEN fail), pls contact Kotak team. Make sure you have selected the correct API endpoint in KotakTrader settings

Check the below folder for files with name 'ONETIMETOKEN' which will have complete error response received from Kotak API
C:\Users\Public\Documents\KotakNet\Kotak\[DDMMMYYYY]\Dumps\
*Replace [DDMMMYYYY] with relevant date

Once you are logged-in to KotakTrader, calling place order bridge function in excel VBA by passing required symbol details will place order.

**_You don't need to use our excel, as replied earlier they are just examples of how to call bridge function in Excel.
You need to know VBA programming to call the Bridge function in your Excel._**

This is not any kind of teaser or incomplete code.
